# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-04 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=100, null=True)),
                ('face_json', models.TextField(blank=True, null=True)),
                ('pic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=4)),
                ('avator', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('0', '正常'), ('1', '锁定')], default='0', max_length=4)),
                ('state', models.CharField(choices=[('0', '普通用户'), ('1', '高级会员')], default='0', max_length=4)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('faceid', models.CharField(blank=True, max_length=128, null=True)),
                ('joined_date1', models.DateField(blank=True, null=True)),
                ('joined_date2', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_member',
                'managed': False,
            },
        ),
    ]
