# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='apimember',
            options={'managed': False, 'ordering': ['id'], 'verbose_name': '会员基本信息', 'verbose_name_plural': '会员基本信息'},
        ),
    ]
