# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-09 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotcommend', '0003_auto_20190309_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hot_list',
            old_name='type',
            new_name='categories',
        ),
    ]
