# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assin', models.CharField(max_length=100)),
                ('present_price', models.FloatField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('imUrl', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('0', '下架'), ('1', '在售'), ('2', '热销')], default='1', max_length=20, verbose_name='商品的状态')),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
        migrations.CreateModel(
            name='Commodity_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0)),
                ('updataTime', models.DateTimeField(auto_now_add=True, verbose_name='价格更新日期')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Commodity')),
            ],
            options={
                'db_table': 'commodity_price',
            },
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'commodity_type',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commodity.CommodityType'),
        ),
    ]
