# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='buyDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='商品购买日期'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='warrantyDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='商品保质日期'),
        ),
    ]
