# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-05 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('product_id_1', models.TextField(blank=True, max_length=100, null=True)),
                ('product_id_2', models.TextField(blank=True, max_length=100, null=True)),
                ('product_id_3', models.TextField(blank=True, null=True)),
                ('product_id_4', models.TextField(blank=True, max_length=1000, null=True)),
                ('product_id_5', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users_recommendations',
            },
        ),
    ]
