# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-01 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190301_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='摄像头路径'),
        ),
    ]
